### ISSUE TITLE
Request for paper or report

### ISSUE THREAD

**Issue by yenanjing** [XiaolongTang23/HPNet#1]
Thanks for your brilliant work and sharing. I am confused of the idea of this repo, how could I read your paper or report? Looking forward to your reply.

**Comment by XiaolongTang23** [comment]
Thank you for your interest and kind words!  The camera-ready version of the paper is currently being prepared and is not available yet.  In the meantime, you might find the preliminary draft on OpenReview useful for understanding our work.  You can access it here: https://openreview.net/pdf?id=nt9YEGfXf3.  Please feel free to reach out if you have any further questions or need more information.

**Comment by yenanjing** [comment]
ok, Thanks!

**Comment by zachytong** [comment]
the access is restricted now, is it possible for author to provide a new one? Thanks!

**Comment by zhengyang-ponyai** [comment]
+1 seems openreview link is a restricted link

**Comment by maybetomorrow99** [comment]
+1. I'm interested in this work. But access to https://openreview.net/pdf?id=nt9YEGfXf3 is restricted. If you can provide a new link it would be great. Thanks! @XiaolongTang23

**Comment by Morphlingxxx** [comment]
+1 openreview cannot download the work

**Comment by XiaolongTang23** [comment]
I'm really sorry. I made a mistake. I have just submitted the article to Arxiv, and it will be available soon.
