### ISSUE TITLE
Is there any mistakes in t2m_heading_t? 

### ISSUE THREAD

**Issue by ilzkl1991** [XiaolongTang23/HPNet#10]
Is there any mistakes in t2m_heading_t? maybe it should be  data['agent']['heading'][:,:self.num_historical_steps].reshape(-1)?
        #t2m edge
        t2m_position_t = data['agent']['position'][:,:self.num_historical_steps].reshape(-1,2)      #[(N1,...,Nb)*H,2]
        t2m_position_m = m_position.reshape(-1,2)                                                   #[(N1,...,Nb)*H*K,2]
        t2m_heading_t = data['agent']['heading'].reshape(-1)                                        #[(N1,...,Nb)]
        t2m_heading_m = m_heading.reshape(-1)                                                       #[(N1,...,Nb)*H*K]
        t2m_valid_mask_t = data['agent']['visible_mask'][:,:self.num_historical_steps]              #[(N1,...,Nb),H]
        t2m_valid_mask_m = m_valid_mask.reshape(num_all_agent,-1)                                   #[(N1,...,Nb),H*K]
        t2m_valid_mask = t2m_valid_mask_t.unsqueeze(2) & t2m_valid_mask_m.unsqueeze(1)              #[(N1,...,Nb),H,H*K]

**Comment by mjZeng11** [comment]
> t2m_heading_t有什么错误吗？也许应该是 data['agent']['heading'][：，：self.num_historical_steps].reshape（-1）？ #t2m 边 t2m_position_t = data['agent']['position'][：，：self.num_historical_steps].reshape（-1,2） #[（N1,...,Nb）_H，2] t2m_position_m = m_position.reshape（-1,2） #[（N1,...,Nb）_H_K，2] t2m_heading_t = data['agent']['heading'].reshape（-1） #[（N1,...,Nb）] t2m_heading_m = m_heading.reshape（-1） #[（N1,...,Nb）_H_K] t2m_valid_mask_t = data['agent']['visible_mask'][：，：self.num_historical_steps] #[（N1,...,Nb），H] t2m_valid_mask_m = m_valid_mask.reshape（num_all_agent，-1） #[（N1,...,Nb），H_K] t2m_valid_mask = t2m_valid_mask_t.unsqueeze（2） & t2m_valid_mask_m.unsqueeze（1） #[（N1,...,Nb），H，H*K]

Hi, has the problem been solved？
