### ISSUE TITLE
Encoding Agent Features.

### ISSUE THREAD

**Issue by ilzkl1991** [XiaolongTang23/HPNet#11]
thank you for your work.

when i read the code, i found that in the paper, the agent features are  the velocity magnitude, the direction of velocity, and the attribute.  but in the code , the agent features are the length of the vector, it seems the features only have the length, without the direction. Can you explain why you don't use the features like vector, velocity?

**Comment by XiaolongTang23** [comment]
I guess you are looking at the HPNet-Argoverse code. The reason we only use the length is that Argoverse does not provide velocity-related information. The INTERACTION dataset does provide these details, and for that dataset, the encoding part uses more information as described in the paper.

**Comment by ilzkl1991** [comment]
> I guess you are looking at the HPNet-Argoverse code. The reason we only use the length is that Argoverse does not provide velocity-related information. The INTERACTION dataset does provide these details, and for that dataset, the encoding part uses more information as described in the paper.

Thank you for your reply.  Do you have tried to convert pth/ckpt to ONNX? If yes, is there any translation problem?

**Comment by XiaolongTang23** [comment]
> > I guess you are looking at the HPNet-Argoverse code. The reason we only use the length is that Argoverse does not provide velocity-related information. The INTERACTION dataset does provide these details, and for that dataset, the encoding part uses more information as described in the paper.
> 
> Thank you for your reply. Do you have tried to convert pth/ckpt to ONNX? If yes, is there any translation problem?

Hi, I have not yet tried converting the model from .pth/.ckpt to ONNX format, so I am unable to provide specific details on potential translation issues. It is certainly an area worth exploring.
