### ISSUE TITLE
代码里的注释

### ISSUE THREAD

**Issue by Family-Liao** [XiaolongTang23/HPNet#14]
麻烦问一下，代码中的注释t2m、l2m、m2m_a、m2m_h、m2m_s、t2n、l2n等是代表什么意思啊！谢谢

**Comment by XiaolongTang23** [comment]
结合论文会更好理解，t2m和l2m分别指time to mode, lane to mode；m2m_a, m2m_h, m2m_s分别指agent attention, historical prediction attention and mode attention。m和n分别是propose和refine阶段对mode query的代称

**Comment by Family-Liao** [comment]
> 结合论文会更好理解，t2m和l2m分别指time to mode, lane to mode；m2m_a, m2m_h, m2m_s分别指agent attention, historical prediction attention and mode attention。m和n分别是propose和refine阶段对mode query的代称


非常感谢你的回复，就是因为重读了一下论文，发现有些首字母代表的含义跟我理解的有点出入，所以就来提一下issue了，再次感谢你们的杰出工作！ @XiaolongTang23

**Comment by Family-Liao** [comment]
作者你好，求助一下，在MapEncoder中的c2l_edge_attr_theta和c2l_edge_attr_heading都是表示一段段中心线的朝向角度吗，看代码看得有点迷糊了，希望赐教一下，万分感谢！ @XiaolongTang23

**Comment by XiaolongTang23** [comment]
> 作者你好，求助一下，在MapEncoder中的c2l_edge_attr_theta和c2l_edge_attr_heading都是表示一段段中心线的朝向角度吗，看代码看得有点迷糊了，希望赐教一下，万分感谢！ @XiaolongTang23

c是指centerline，l是指lane segment，c2l_edge_attr指的是centerline point到所属lane segment的边的属性，c2l_edge_attr_theta是边在该lane segment参考系下的朝向，而heading是该centerline point在所属lane segment参考系下的朝向，这两个朝向对于lane segment获取其包含的centerline point都很重要

**Comment by Family-Liao** [comment]
> > 作者你好，求助一下，在MapEncoder中的c2l_edge_attr_theta和c2l_edge_attr_heading都是表示一段段中心线的朝向角度吗，看代码看得有点迷糊了，希望赐教一下，万分感谢！ @XiaolongTang23
> 
> c是指centerline，l是指lane segment，c2l_edge_attr指的是centerline point到所属lane segment的边的属性，c2l_edge_attr_theta是边在该lane segment参考系下的朝向，而heading是该centerline point在所属lane segment参考系下的朝向，这两个朝向对于lane segment获取其包含的centerline point都很重要

首先感谢你的回复，上午结合gpt分析了def transform_point_to_local_coordinate()该方法的作用，再结合你给出的回复，我说说我的理解，您帮忙看看对不对：c2l_edge_attr_theta就是每个中心线的点在它们自己对应的lane segment参考坐标系(将lane segment 作为原点的local_coordinate)下的朝向，而c2l_edge_attr_heading则是每个中心线的点在全局参考坐标系(global coordinate)下的朝向并受到对应lane segment的朝向范围限制，因为代码里带上了wrap_angle()方法。麻烦你评价一下我理解得是否正确！ @XiaolongTang23

**Comment by XiaolongTang23** [comment]
> > > 作者你好，求助一下，在MapEncoder中的c2l_edge_attr_theta和c2l_edge_attr_heading都是表示一段段中心线的朝向角度吗，看代码看得有点迷糊了，希望赐教一下，万分感谢！ @XiaolongTang23
> > 
> > 
> > c是指centerline，l是指lane segment，c2l_edge_attr指的是centerline point到所属lane segment的边的属性，c2l_edge_attr_theta是边在该lane segment参考系下的朝向，而heading是该centerline point在所属lane segment参考系下的朝向，这两个朝向对于lane segment获取其包含的centerline point都很重要
> 
> 首先感谢你的回复，上午结合gpt分析了def transform_point_to_local_coordinate()该方法的作用，再结合你给出的回复，我说说我的理解，您帮忙看看对不对：c2l_edge_attr_theta就是每个中心线的点在它们自己对应的lane segment参考坐标系(将lane segment 作为原点的local_coordinate)下的朝向，而c2l_edge_attr_heading则是每个中心线的点在全局参考坐标系(global coordinate)下的朝向并受到对应lane segment的朝向范围限制，因为代码里带上了wrap_angle()方法。麻烦你评价一下我理解得是否正确！ @XiaolongTang23

我感觉可能不太对，c和l都有各自的方向，c2l_edge_attr_heading表示c相对l的角度，c2l_edge_attr_theta则表示连接c和l的边在l参考系下的角度

**Comment by Family-Liao** [comment]
明白了，谢谢大佬这么晚还回复！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiaolongTang23/HPNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月17日(星期三) 凌晨0:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XiaolongTang23/HPNet] 代码里的注释 (Issue #14)





    
作者你好，求助一下，在MapEncoder中的c2l_edge_attr_theta和c2l_edge_attr_heading都是表示一段段中心线的朝向角度吗，看代码看得有点迷糊了，希望赐教一下，万分感谢！ @XiaolongTang23
  
c是指centerline，l是指lane segment，c2l_edge_attr指的是centerline point到所属lane segment的边的属性，c2l_edge_attr_theta是边在该lane segment参考系下的朝向，而heading是该centerline point在所属lane segment参考系下的朝向，这两个朝向对于lane segment获取其包含的centerline point都很重要
  
首先感谢你的回复，上午结合gpt分析了def transform_point_to_local_coordinate()该方法的作用，再结合你给出的回复，我说说我的理解，您帮忙看看对不对：c2l_edge_attr_theta就是每个中心线的点在它们自己对应的lane segment参考坐标系(将lane segment 作为原点的local_coordinate)下的朝向，而c2l_edge_attr_heading则是每个中心线的点在全局参考坐标系(global coordinate)下的朝向并受到对应lane segment的朝向范围限制，因为代码里带上了wrap_angle()方法。麻烦你评价一下我理解得是否正确！ @XiaolongTang23
  
我感觉可能不太对，c和l都有各自的方向，c2l_edge_attr_heading表示c相对l的角度，c2l_edge_attr_theta则表示连接c和l的边在l参考系下的角度

**Comment by EroicaX** [comment]
@XiaolongTang23 作者你好，我看代码里的m2m_h编码用的信息似乎并不是历史预测结果，而仍然是agent的历史轨迹即m_position等，请问下论文里的historical prediction embedding在代码里是怎么体现的呢？

**Comment by LongLiveForFreedom** [comment]
我之前也有同样的疑问，跟别的大佬讨论后的结果是HPNet是进行了两个阶段的编码，第一个阶段就像laneGCN那样编码，直接解码的话就是预测结果，第二阶段用了第一阶段的编码结果，所以算作历史预测

**Comment by EroicaX** [comment]
邮件已收到，谢谢

**Comment by EroicaX** [comment]
m和n两个阶段应该是类似于QCNet里面的轨迹proposal和refine的关系，论文里的Historical Prediction从描述上来看应该是模型输出的对前一段时域预测的结果，这个点没太看出来
