### ISSUE TITLE
关于模型集成

### ISSUE THREAD

**Issue by XinGP** [XiaolongTang23/HPNet#15]
作者您好！非常感谢您公开了您的代码成果，请问模型集成这一块的细节可否透露一些吗？是通过多次训练得到的模型还是一次训练得到的模型进行集成的呢？具体需要多少个模型来集成比较合适？

**Comment by XiaolongTang23** [comment]
集成自然需要多次训练的模型，通常是不同的随机种子训练的模型。由于HPNet方法得到的结果比较稳定，我们也对网络结构进行了小的修改从而得到更多样的预测。最后一共用了10个模型来集成。不过即使这样做了，其实相比集成前的提升也并不大，说明我们采用的集成策略可能并不太好，仅供您参考

**Comment by XinGP** [comment]
好的，感谢作者分享，还有一个小问题，就是我看你是把单个模型和集成模型分开进行了比较。但是你怎么知道哪些模型是用了集成呢（比如qcnet和wayformer）？

**Comment by XiaolongTang23** [comment]
通常论文中会对是否使用集成进行描述，只是有的比较详细，有的比较简略。Wayformer在论文的"Training Details and Hyperparameters"部分对集成进行了说明，而QCNet则在补充材料中进行了说明。
