### ISSUE TITLE
question about I_1 and I_2

### ISSUE THREAD

**Issue by nchuly** [XiaolongTang23/HPNet#17]
thanks for sharing your excellent work.i was wondering if you could tell me the value of I_1 and I_2 during your experiment. i am a little confused.

**Comment by nchuly** [comment]
as in Eq(7) and Eq(4),  when  I2 = I1,why the observation window of Historical Prediction Attention is twice as long, i.e., [t − I1 − I1, t]?

**Comment by XiaolongTang23** [comment]
Apologies for the delayed response. In our experiments, both I_1 and I_2 are set to 20. The reason Historical Prediction Attention extends the observation window is that the prediction embedding at the farthest timestep t-I_2  already incorporates attention information from the frames within [t-I_2-I_1, t-I_2] via Spatio-Temporal Attention. This mechanism allows Historical Prediction Attention to effectively broaden the observation range.
