### ISSUE TITLE
How to implement ensemble

### ISSUE THREAD

**Issue by yenanjing** [XiaolongTang23/HPNet#2]
I noticed that you submitted results using ensemble on the leaderboard, but I'm not sure how to implement it. I tried using QCNet for ensemble, but the results were very poor. I look forward to your guidance.

**Comment by XiaolongTang23** [comment]
I recommend you refer to the supplementary material of QCNet, where their ensembling method is detailed.

**Comment by yenanjing** [comment]
> supplementary materia

Thank you for your reply. I have found it. Thanks again!
