### ISSUE TITLE
test result

### ISSUE THREAD

**Issue by wan-yujun** [XiaolongTang23/HPNet#21]
I would like to ask, your val can reproduce the results, but the test results do not. The test only generates files for H5. How can we reproduce the test results

**Comment by wan-yujun** [comment]
![123](https://github.com/user-attachments/assets/44befd28-5b5d-4793-b1b3-1a962121e8c6)
How can we reproduce the test results？

**Comment by XiaolongTang23** [comment]
To reproduce the test results, you need to generate the H5 files and submit them to the Argoverse Motion Forecasting Challenge on EvalAI to obtain the evaluation results.  You can refer to the following link for more details: https://eval.ai/web/challenges/challenge-page/454/leaderboard.
