### ISSUE TITLE
Question about the temporal span I1 and I2

### ISSUE THREAD

**Issue by chantsss** [XiaolongTang23/HPNet#6]
Thanks for sharing your excellent work as open source. I have a question about your code. I couldn't find the specific parameters for the temporal span **I1** and **I2** that you mentioned in your paper. Could you please explain how to pass them and how they work in the attention mechanism?

**Comment by XiaolongTang23** [comment]
I apologize for any confusion caused by the terminology used in our paper.   The parameters referred to as "temporal span I1 and I2" in the paper are named pos_duration and pred_duration in the code.   These parameters control the window size for past positions and past predictions, respectively.

**Comment by chantsss** [comment]
Thank you for your prompt response.  Just one more question, I see the pos_duration I1 defaults 20, which is already the maximum value for history length. In other words, the window size for past positions is [t − I1, t]==>[t − 20, t]. In such case, t − I1− I2<t − 20, and it is out of the interval [t − 20, t]. How do you handle such case?

**Comment by XiaolongTang23** [comment]
You are right. During normal training, although the visible window is larger, we are limited to only the 20 frames of data. However, in the experimental section of our work, I set a longer history length to test the advantages of a larger visible window. For more details, you can refer to Figure 3 in the paper.
