### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by xiaowuge1201** [XiaolongTang23/HPNet#8]
I don't know how to perform serial deployment to reduce inference time. Can you provide a detailed idea?? Thank you very much

**Comment by penglo** [comment]
> I don't know how to perform serial deployment to reduce inference time. Can you provide a detailed idea?? Thank you very much

I'd also like to know how this issue is handled. If you're interested, you can give me your email or send an email to my inbox so we can discuss it together.
My email is lipl23@mails.jlu.edu.cn. Thank you.

**Comment by xiaowuge1201** [comment]
> > I don't know how to perform serial deployment to reduce inference time. Can you provide a detailed idea?? Thank you very much
> 
> I'd also like to know how this issue is handled. If you're interested, you can give me your email or send an email to my inbox so we can discuss it together. My email is [lipl23@mails.jlu.edu.cn](mailto:lipl23@mails.jlu.edu.cn). Thank you.

My email is wangqw2685@163.com 
If you have any ideas about this, you can guide me. Thanks

**Comment by XiaolongTang23** [comment]
Hi, thank you for your question.
In parallel deployment, the model predicts trajectories of multiple time steps simultaneously. In serial deployment, the model makes sequential predictions for each time step, which can improve the reasoning speed. To implement serial deployment, you need to implement the model in a circular manner and save the results of the previous time step.

**Comment by guoyh6** [comment]
> Hi, thank you for your question. In parallel deployment, the model predicts trajectories of multiple time steps simultaneously. In serial deployment, the model makes sequential predictions for each time step, which can improve the reasoning speed. To implement serial deployment, you need to implement the model in a circular manner and save the results of the previous time step.

Hi, I just learned about this field. Can you explain why serial reasoning is faster? Thanks a lot!
