### ISSUE TITLE
Code for Argoverse2 and WOMD

### ISSUE THREAD

**Issue by youngzhou1999** [XiaolongTang23/HPNet#9]
Hi, xiaolong. Thanks for the great paper and code.

I notice that you have tried to run HPNet on Argoverse2 and WOMD from [https://github.com/XiaolongTang23/HPNet/issues/4](https://github.com/XiaolongTang23/HPNet/issues/4).
Recently, I've been doing projects based on your HPNet as an advanced backbone model. We would love to deeply reference your paper and model in our project. However, handling the data process and hyper-parameters is a little tricky for different datasets. Is there any chance I can acquire the HPNet code for Argoverse2 and WOMD? It will benefit me much and save me time.

Also, I've sent an email to you.
Thanks again for the convenient code. I hope to hear from you soon. :smiley:

**Comment by XiaolongTang23** [comment]
Hello, thank you for your interest in our work.

I have indeed run on AV2 and Waymo, but I haven't organized the code for these two datasets yet, so it might not be convenient to share it.   However, the backbone has not changed significantly;   the main difference lies in the dataset processing.   You can refer to the dataset processing part of the QCNet project.   Regarding hyperparameters, I encountered OOM (Out of Memory) issues when running on these two datasets, so I only managed to run them with a small hidden_dim and almost didn't tune the parameters.   Therefore, I may not be able to help you with this part.

**Comment by youngzhou1999** [comment]
Thanks for your reply. I'll refer to the QCNet project for dataset processing.

And good luck to you in successfully running HPNet on Argoverse2 and Waymo. It would be pretty cool.
